 CREATE TABLE "FIVE"."MEMMANAGE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"AGE" NUMBER(*,0), 
	"GENDER" VARCHAR2(20 BYTE), 
	"NUM" NUMBER(*,0), 
	"ADDRESS" VARCHAR2(50 BYTE)
	INFO VARCHAR2(50 BYTE) 
   )